---
- name: Capture alertmanager alerts
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true

  rules:

    - name: SELinux was enabled
      condition: event.alert.labels.alertname == "selinux disabled" and event.alert.status == "resolved"
      action:
        debug:
          msg: "enabled on: {{ event.meta.hosts }}"

    - name: Capture all other events from this source
      condition: event.alert is defined
      action:
        debug:
