---
- name: Listen to Netbox webhooks
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003

  rules:
    - name: IP address changed
      condition: event.payload.model == 'ipaddress' and event.payload.user == 'admin'
      action:
        run_job_template:
          name: "NETBOX 04 - push L3 intf"
          organization: Default
          job_args:
            extra_vars: "{{ event.payload }}"
            limit: "{{ event.payload.host }}"

    - name: Interface configuration and Layer 2
      condition: event.payload.model == 'interface' and event.payload.user == 'admin'
      action:
        run_job_template:
          name: "NETBOX 03 - push L2 intf"
          organization: Default
          job_args:
            extra_vars: "{{ event.payload }}"
            limit: "{{ event.payload.host }}"

    - name: Did not match any model
      condition: event.payload is defined
      action:
        debug:
