---
# {"payload":{"msg":"Configured from console by cisco on vty0 (172.16.1.1)","host":"ios-rt1"}}
- name: Listen to Syslog requests
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:

    # - name: Capture all events from this source
    #   condition: true
    #   action:
    #     debug:

    - name: Parse Interfaces for a single host
      condition: event.payload.msg is search("cisco")
      action:
        run_job_template:
          name: "NETBOX 02 - parse intfs"
          organization: Default
          job_args:
            limit: "{{ event.payload.host }}"
            extra_vars: "{{ event.payload }}"
