---
- name: Listen to Syslog requests
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:

    - name: Capture all events from this source
      condition: true
      action:
        debug:

    - name: Parse Interfaces for a single host
      condition: true
      # condition: event.payload.message == "Ansible is super cool"
      action:
        run_job_template:
          name: MERAKI 00 - get org ID
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
