---
- name: Listen to Syslog requests
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:

    - name: Parse Interfaces for a single host
      condition: event.payload.message == "Ansible is super cool"
      action:
        run_job_template:
          name: "NETBOX 02 - parse intfs"
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
