---
- name: Test Webhook 5000
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002
  rules:

    - name: Capture all events from this source
      condition: true
      action:
        debug:

    # - name: Parse Interfaces for a single host
    #   condition: event.payload.message == "Ansible is super cool"
    #   action:
    #     run_job_template:
    #       name: "NETBOX 02 - parse intfs"
    #       organization: Default
    #       job_args:
    #         limit: "{{ event.meta.hosts }}"
